#!/usr/bin/bash
a=0
# -lt is less than operator
 
#Iterate the loop until a less than 10
while [ $a -lt 29 ]
do
    # Print the values
    touch $a-answer.txt
    code $a-answer.txt
     
    # increment the value
    a=`expr $a + 1`
done